export enum Positions {
  SUPERINTENDENT = 1,
  SENIOR_DISPATCH_ENGINEER = 2,
  SENIOR_MINING_ENGINEER = 3,
  SPECIALIST_DISPATCH = 4,
  SUPERVISOR = 5,
  TRINER = 6,
  GDP = 7,
  DISPATCHER = 8,
  ASSISTANT_DISPATCHER = 9,
  OPERATOR_MAGANG = 10,
}
